[versions]
assertj = "3.27.6"
awaitility = "4.3.0"
jackson2 = "2.20.1"
jackson3 = "3.0.3"
jacoco = "0.8.14"
jreleaser = "1.20.0"
jspecify = "1.0.0"
junit = "6.0.1"
lombok = "1.18.42"
lombok-gradle = "9.1.0"
module-info = "1.13.1"
semver4j = "6.0.0"
slf4j = "2.0.17"
testcontainers = "2.0.2"
quarkus = "3.30.3"
quarkus-github-api = "1.330.0"
quarkus-wiremock = "1.5.2"

[libraries]
# assertj
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

# awaitility
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }

# lombok-gradle
lombok-gradle = { group = "io.freefair.lombok", name = "io.freefair.lombok.gradle.plugin", version.ref = "lombok-gradle" }

# Jackson
jackson-annotations = { group = "com.fasterxml.jackson.core", name = "jackson-annotations" }
jackson-bom = { group = "tools.jackson", name = "jackson-bom", version.ref = "jackson3" }
jackson2-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson2" }
jackson-databind = { group = "tools.jackson.core", name = "jackson-databind" }
jackson2-databind = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson2" }

# JSpecify
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }

# JReleaser
jreleaser-gradle-plugin = { group = "org.jreleaser", name = "jreleaser-gradle-plugin", version.ref = "jreleaser" }

# JUnit
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

# SLF4j
slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

# Testcontainers
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers"}
testcontainers-junit-jupiter = { group = "org.testcontainers", name = "testcontainers-junit-jupiter" }
semver4j = { group = "org.semver4j", name = "semver4j", version.ref = "semver4j" }

# Quarkus
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "quarkus" }
quarkus-wiremock = { group = "io.quarkiverse.wiremock", name = "quarkus-wiremock", version.ref = "quarkus-wiremock" }
quarkus-github-api = { group = "io.quarkiverse.githubapi", name = "quarkus-github-api", version.ref = "quarkus-github-api" }
quarkus-wiremock-test = { group = "io.quarkiverse.wiremock", name = "quarkus-wiremock-test", version.ref = "quarkus-wiremock" }

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok-gradle" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
module-info = { id = "org.gradlex.extra-java-module-info", version.ref = "module-info" }
