name: Simple build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  save-pr-info:
    runs-on: ubuntu-latest
    if: always() && (github.event_name == 'pull_request')
    needs: jvm-build-test
    steps:
      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.number }} > ./pr/number
          echo ${{ github.event.pull_request.head.sha }} > ./pr/sha

      - name: Upload PR metadata
        uses: actions/upload-artifact@v5
        with:
          name: pr-metadata
          path: pr/
          retention-days: 7

  jvm-build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
          - 21
          - 25
        module:
          - docling-serve-api
          - docling-serve-client
          - docling-testcontainers
          - docling-version-tests
    name: jvm-build-test-${{ matrix.module }}-java${{ matrix.java }}
    steps:
      - uses: actions/checkout@v5

      - name: Reclaim disk space
        working-directory: .github
        shell: bash
        run: ./ci-reclaim-disk-space.sh

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: build-test-${{ matrix.module }}-java${{ matrix.java }}
        run: |
          ./gradlew --no-daemon -Pjava.version=${{ matrix.java }} \
            :${{ matrix.module }}:clean :${{ matrix.module }}:build

  prepare-test-reports:
    runs-on: ubuntu-latest
    if: always() && (github.event_name == 'pull_request')
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
          - 21
          - 25
    steps:
      - uses: actions/checkout@v5

      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Create aggregated test report
        run: ./gradlew --no-daemon -Pjava.version=${{ matrix.java }} :test-report-aggregation:check

      - name: Prepare build reports
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: build-reports-java${{ matrix.java }}-${{ github.run_attempt }}
          path: |
            **/build/test-results/**/*.xml
            test-report-aggregation/build/reports/tests/test/aggregated-results/**
          retention-days: 7

  docs:
    runs-on: ubuntu-latest
    name: build-docs-pr
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Setup Java 25
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle

      - name: Generate documentation
        run: ./gradlew --console=plain clean :docs:build
