name: Publish docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types:
      - released

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Build/publish Docs
    if: github.repository == 'docling-project/docling-java'
    steps:
      - name: Setup env (release)
        if: github.event_name == 'release'
        run: echo "DOCS_ALIAS=current" >> $GITHUB_ENV

      - name: Setup env (other)
        if: (github.event_name != 'release')
        run: echo "DOCS_ALIAS=dev" >> $GITHUB_ENV

      - name: Checkout sources
        if: github.event_name != 'release'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          path: app

      - name: Get release sources
        if: github.event_name == 'release'
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name }}
          path: app

      - name: Get docs
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: gh-pages
          path: docs

      - name: Setup Python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: '3.x'

      - name: Setup Java 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Show current docs
        run: |
          tree ${{ github.workspace }}/docs
          cat ${{ github.workspace }}/docs/versions.json

      - name: Generate documentation
        working-directory: app
        run: |
          ./gradlew --console=plain :docs:build \
            -Pdocs.alias=${{ env.DOCS_ALIAS }} \
            -Pdocs.versionsFile=${{ github.workspace }}/docs/versions.json

      - name: Copy to gh-pages
        run: cp -Rf app/docs/build/mkdocs/* docs/

      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ vars.DOCLING_JAVA_CI_APP_ID }}
          private-key: ${{ secrets.DOCLING_JAVA_CI_PRIVATE_KEY }}

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: docs
          commit-message: "docs: Build and publish docs (from ${{ github.workflow }} run # ${{ github.run_number }})"
          branch: build-docs/sourceref
          branch-suffix: short-commit-hash
          delete-branch: true
          base: gh-pages
          signoff: true
          sign-commits: true
          title: "docs: Build and publish docs (from ${{ github.workflow }} run # ${{ github.run_number }})"
          body: "docs: Build and publish docs from [${{ github.workflow }} run # ${{ github.run_number }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}), which was triggered by commit ${{ env.REF }}."
          labels: documentation

      - name: Merge PR
        if: (steps.create-pr.outputs.pull-request-operation == 'created') && steps.create-pr.outputs.pull-request-number
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh pr merge --merge --admin --delete-branch "${{ steps.create-pr.outputs.pull-request-url }}"
