name: Perform release

env:
  JAVA_VERSION: 17

on:
  pull_request:
    types:
      - closed
    paths:
      - .github/project.yml
  workflow_dispatch:
    inputs:
      version:
        description: The version to release (e.g. 1.0.0)
        required: true
        type: string
      dryrun:
        description: Perform a dry-run release
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  attestations: write
  id-token: write
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    if: (github.repository == 'docling-project/docling-java') && ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'pull_request') && (github.event.pull_request.merged == true)))
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.DOCLING_JAVA_CI_APP_ID }}
          private-key: ${{ secrets.DOCLING_JAVA_CI_PRIVATE_KEY }}

      - name: Checkout before PR
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: before
          token: ${{ steps.app-token.outputs.token }}

      - name: Checkout current ref
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}
          path: before
          token: ${{ steps.app-token.outputs.token }}

      - name: Capture version before PR
        if: github.event_name == 'pull_request'
        run: echo "PREVIOUS_VERSION=$(yq '.release.current-version' before/.github/project.yml)" >> $GITHUB_ENV

      - name: Set version to release
        if: github.event_name == 'workflow_dispatch'
        run: echo "PREVIOUS_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
    
      - name: Checkout current ref
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: after

      - name: Capture current version
        run: echo "CURRENT_VERSION=$(yq '.release.current-version' after/.github/project.yml)" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build artifacts
        working-directory: before
        run: ./gradlew --no-daemon -Pjava.version=${{ env.JAVA_VERSION }} publish

      - name: Release
        working-directory: before
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_DRY_RUN: ${{ inputs.dryrun }}
        run: |
          echo "Releasing version ${{ env.PREVIOUS_VERSION }} -> ${{ env.CURRENT_VERSION }}"
          ./gradlew --no-daemon :jreleaserFullRelease
