name: Perform release

env:
  JAVA_VERSION: 17

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths:
      - .github/project.yml
  workflow_dispatch:
    inputs:
      version:
        description: The version to release (e.g. 1.0.0)
        required: true
        type: string
      dryrun:
        description: Perform a dry-run release
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  attestations: write
  id-token: write
  contents: write

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    if: (github.repository == 'docling-project/docling-java') && ((github.event_name == 'workflow_dispatch') || ((github.event_name == 'pull_request_target') && (github.event.pull_request.merged == true)))
    steps:
      - uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94 # v2.2.0
        id: app-token
        with:
          app-id: ${{ vars.DOCLING_JAVA_CI_APP_ID }}
          private-key: ${{ secrets.DOCLING_JAVA_CI_PRIVATE_KEY }}

      - name: Checkout before PR
        if: github.event_name == 'pull_request_target'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: before
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Checkout current ref
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ github.ref }}
          path: before
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Capture version before PR
        if: github.event_name == 'pull_request_target'
        run: echo "PREVIOUS_VERSION=$(yq '.release.current-version' before/.github/project.yml)" >> $GITHUB_ENV

      - name: Set version to release
        if: github.event_name == 'workflow_dispatch'
        run: echo "PREVIOUS_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
    
      - name: Checkout current ref
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          path: after
          fetch-depth: 0

      - name: Capture current version
        run: echo "CURRENT_VERSION=$(yq '.release.current-version' after/.github/project.yml)" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build artifacts
        working-directory: before
        run: ./gradlew --no-daemon -Pjava.version=${{ env.JAVA_VERSION }} publish

      - name: Release
        working-directory: before
        env:
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_DISCORD_WEBHOOK: ${{ secrets.RELEASES_DISCORD_WEBHOOK }}
          JRELEASER_DRY_RUN: ${{ inputs.dryrun }}
        run: |
          echo "Releasing version ${{ env.PREVIOUS_VERSION }} -> ${{ env.CURRENT_VERSION }}"
          ./gradlew --no-daemon :jreleaserFullRelease

      # Persist logs
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: jreleaser-release
          path: |
            build/jreleaser/trace.log
            build/jreleaser/output.properties
